
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action Action;

	private global::Gtk.Action newAction;

	private global::Gtk.Action openAction;

	private global::Gtk.Action saveAction;

	private global::Gtk.Action saveAsAction;

	private global::Gtk.Action quitAction;

	private global::Gtk.Action propertiesAction;

	private global::Gtk.Action printAction;

	private global::Gtk.Action quitAction1;

	private global::Gtk.HBox hbox4;

	private global::Gtk.VBox vbox4;

	private global::Gtk.HBox hbox5;

	private global::Gtk.VBox vbox5;

	private global::Gtk.CheckButton checkbutton2;

	private global::Gtk.ComboBox CBView1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.DrawingArea DA2;

	private global::Gtk.VScrollbar vsda2;

	private global::Gtk.HScrollbar hsda2;

	private global::Gtk.HBox hbox6;

	private global::Gtk.VBox vbox7;

	private global::Gtk.ComboBox CBView3;

	private global::Gtk.CheckButton checkbutton4;

	private global::Gtk.HScrollbar hsda3;

	private global::Gtk.HBox hbox3;

	private global::Gtk.DrawingArea DA3;

	private global::Gtk.VScrollbar vsda3;

	private global::Gtk.VBox vbox1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox10;

	private global::Gtk.VBox vbox9;

	private global::Gtk.HBox hbox11;

	private global::Gtk.ComboBox cmbFaceSelection;

	private global::Gtk.Image image16;

	private global::Gtk.HBox hbox13;

	private global::Gtk.ColorButton clrSelection;

	private global::Gtk.Image image17;

	private global::Gtk.VBox vbox10;

	private global::Gtk.HBox hbox17;

	private global::Gtk.Label label11;

	private global::Gtk.SpinButton spnSectorSelector;

	private global::Gtk.Image image257;

	private global::Gtk.VBox vbox11;

	private global::Gtk.ComboBox cmbEditMode;

	private global::Gtk.Button newSectorBtn;

	private global::Gtk.Button btnAddSolid;

	private global::Gtk.Button cmdAddDoor;

	private global::Gtk.Button addLampBtn;

	private global::Gtk.Button button1;

	private global::Gtk.HBox hbox16;

	private global::Gtk.Label label1;

	private global::Gtk.SpinButton spnActorCandelas;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.Button newMapBtn;

	private global::Gtk.Button openMapBtn;

	private global::Gtk.Button btnImportLevel;

	private global::Gtk.Button saveAsBtn;

	private global::Gtk.Button btnExport;

	private global::Gtk.Button cmdQuit;

	private global::Gtk.Statusbar status;

	private global::Gtk.Image image92;

	private global::Gtk.Label lblCursorX;

	private global::Gtk.Label lblCursorY;

	private global::Gtk.Label lblCursorZ;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.Action = new global::Gtk.Action ("Action", null, null, null);
		w1.Add (this.Action, null);
		this.newAction = new global::Gtk.Action ("newAction", null, null, "gtk-new");
		w1.Add (this.newAction, null);
		this.openAction = new global::Gtk.Action ("openAction", null, null, "gtk-open");
		w1.Add (this.openAction, null);
		this.saveAction = new global::Gtk.Action ("saveAction", null, null, "gtk-save");
		w1.Add (this.saveAction, null);
		this.saveAsAction = new global::Gtk.Action ("saveAsAction", null, null, "gtk-save-as");
		w1.Add (this.saveAsAction, null);
		this.quitAction = new global::Gtk.Action ("quitAction", null, null, "gtk-quit");
		w1.Add (this.quitAction, null);
		this.propertiesAction = new global::Gtk.Action ("propertiesAction", null, null, "gtk-properties");
		w1.Add (this.propertiesAction, null);
		this.printAction = new global::Gtk.Action ("printAction", null, null, "gtk-print");
		w1.Add (this.printAction, null);
		this.quitAction1 = new global::Gtk.Action ("quitAction1", null, null, "gtk-quit");
		w1.Add (this.quitAction1, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MonoBED2");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("mono2icon.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 800;
		this.DefaultHeight = 480;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.checkbutton2 = new global::Gtk.CheckButton ();
		this.checkbutton2.CanFocus = true;
		this.checkbutton2.Name = "checkbutton2";
		this.checkbutton2.Label = global::Mono.Unix.Catalog.GetString ("Visible");
		this.checkbutton2.Active = true;
		this.checkbutton2.DrawIndicator = true;
		this.checkbutton2.UseUnderline = true;
		this.vbox5.Add (this.checkbutton2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.checkbutton2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.CBView1 = global::Gtk.ComboBox.NewText ();
		this.CBView1.AppendText (global::Mono.Unix.Catalog.GetString ("XZ"));
		this.CBView1.AppendText (global::Mono.Unix.Catalog.GetString ("XY"));
		this.CBView1.AppendText (global::Mono.Unix.Catalog.GetString ("YZ"));
		this.CBView1.AppendText (global::Mono.Unix.Catalog.GetString ("Isometric View"));
		this.CBView1.Name = "CBView1";
		this.CBView1.Active = 0;
		this.vbox5.Add (this.CBView1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.CBView1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.DA2 = new global::Gtk.DrawingArea ();
		this.DA2.Events = ((global::Gdk.EventMask)(4194302));
		this.DA2.Name = "DA2";
		this.hbox2.Add (this.DA2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.DA2]));
		w4.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vsda2 = new global::Gtk.VScrollbar (null);
		this.vsda2.Name = "vsda2";
		this.vsda2.Adjustment.Upper = 255;
		this.vsda2.Adjustment.PageIncrement = 10;
		this.vsda2.Adjustment.PageSize = 10;
		this.vsda2.Adjustment.StepIncrement = 1;
		this.vsda2.Adjustment.Value = 4.64158883361278;
		this.hbox2.Add (this.vsda2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vsda2]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox5.Add (this.hbox2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox2]));
		w6.Position = 2;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hsda2 = new global::Gtk.HScrollbar (null);
		this.hsda2.Name = "hsda2";
		this.hsda2.Adjustment.Upper = 255;
		this.hsda2.Adjustment.PageIncrement = 10;
		this.hsda2.Adjustment.PageSize = 10;
		this.hsda2.Adjustment.StepIncrement = 1;
		this.hsda2.Adjustment.Value = 46.4158883361277;
		this.vbox5.Add (this.hsda2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hsda2]));
		w7.PackType = ((global::Gtk.PackType)(1));
		w7.Position = 3;
		w7.Expand = false;
		w7.Fill = false;
		this.hbox5.Add (this.vbox5);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox5]));
		w8.Position = 0;
		this.vbox4.Add (this.hbox5);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox5]));
		w9.Position = 0;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.CBView3 = global::Gtk.ComboBox.NewText ();
		this.CBView3.AppendText (global::Mono.Unix.Catalog.GetString ("XZ"));
		this.CBView3.AppendText (global::Mono.Unix.Catalog.GetString ("XY"));
		this.CBView3.AppendText (global::Mono.Unix.Catalog.GetString ("YZ"));
		this.CBView3.AppendText (global::Mono.Unix.Catalog.GetString ("Isometric View"));
		this.CBView3.Name = "CBView3";
		this.CBView3.Active = 2;
		this.vbox7.Add (this.CBView3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.CBView3]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.checkbutton4 = new global::Gtk.CheckButton ();
		this.checkbutton4.CanFocus = true;
		this.checkbutton4.Name = "checkbutton4";
		this.checkbutton4.Label = global::Mono.Unix.Catalog.GetString ("Visible");
		this.checkbutton4.Active = true;
		this.checkbutton4.DrawIndicator = true;
		this.checkbutton4.UseUnderline = true;
		this.vbox7.Add (this.checkbutton4);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.checkbutton4]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hsda3 = new global::Gtk.HScrollbar (null);
		this.hsda3.Name = "hsda3";
		this.hsda3.Adjustment.Upper = 255;
		this.hsda3.Adjustment.PageIncrement = 10;
		this.hsda3.Adjustment.PageSize = 10;
		this.hsda3.Adjustment.StepIncrement = 1;
		this.vbox7.Add (this.hsda3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hsda3]));
		w12.PackType = ((global::Gtk.PackType)(1));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.DA3 = new global::Gtk.DrawingArea ();
		this.DA3.Events = ((global::Gdk.EventMask)(4194302));
		this.DA3.Name = "DA3";
		this.hbox3.Add (this.DA3);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.DA3]));
		w13.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vsda3 = new global::Gtk.VScrollbar (null);
		this.vsda3.Name = "vsda3";
		this.vsda3.Adjustment.Upper = 255;
		this.vsda3.Adjustment.PageIncrement = 10;
		this.vsda3.Adjustment.PageSize = 10;
		this.vsda3.Adjustment.StepIncrement = 1;
		this.hbox3.Add (this.vsda3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vsda3]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox7.Add (this.hbox3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox3]));
		w15.PackType = ((global::Gtk.PackType)(1));
		w15.Position = 3;
		this.hbox6.Add (this.vbox7);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.vbox7]));
		w16.Position = 0;
		this.vbox4.Add (this.hbox6);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox6]));
		w17.Position = 1;
		this.hbox4.Add (this.vbox4);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox4]));
		w18.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox ();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.cmbFaceSelection = global::Gtk.ComboBox.NewText ();
		this.cmbFaceSelection.AppendText (global::Mono.Unix.Catalog.GetString ("North (0)"));
		this.cmbFaceSelection.AppendText (global::Mono.Unix.Catalog.GetString ("West (1)"));
		this.cmbFaceSelection.AppendText (global::Mono.Unix.Catalog.GetString ("South (2)"));
		this.cmbFaceSelection.AppendText (global::Mono.Unix.Catalog.GetString ("East (3)"));
		this.cmbFaceSelection.AppendText (global::Mono.Unix.Catalog.GetString ("Floor (4)"));
		this.cmbFaceSelection.AppendText (global::Mono.Unix.Catalog.GetString ("Ceiling (5)"));
		this.cmbFaceSelection.Name = "cmbFaceSelection";
		this.cmbFaceSelection.Active = 0;
		this.hbox11.Add (this.cmbFaceSelection);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.cmbFaceSelection]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.image16 = new global::Gtk.Image ();
		this.image16.Name = "image16";
		this.image16.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-up", global::Gtk.IconSize.Menu);
		this.hbox11.Add (this.image16);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.image16]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox9.Add (this.hbox11);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox11]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox ();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.clrSelection = new global::Gtk.ColorButton ();
		this.clrSelection.CanFocus = true;
		this.clrSelection.Events = ((global::Gdk.EventMask)(784));
		this.clrSelection.Name = "clrSelection";
		this.hbox13.Add (this.clrSelection);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.clrSelection]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.image17 = new global::Gtk.Image ();
		this.image17.Name = "image17";
		this.image17.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-color-picker", global::Gtk.IconSize.Menu);
		this.hbox13.Add (this.image17);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.image17]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox9.Add (this.hbox13);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox13]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		this.hbox10.Add (this.vbox9);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.vbox9]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.vbox10 = new global::Gtk.VBox ();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.hbox17 = new global::Gtk.HBox ();
		this.hbox17.Name = "hbox17";
		this.hbox17.Spacing = 6;
		// Container child hbox17.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Sector:");
		this.hbox17.Add (this.label11);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.label11]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox17.Gtk.Box+BoxChild
		this.spnSectorSelector = new global::Gtk.SpinButton (0, 100, 1);
		this.spnSectorSelector.CanFocus = true;
		this.spnSectorSelector.Name = "spnSectorSelector";
		this.spnSectorSelector.Adjustment.PageIncrement = 10;
		this.spnSectorSelector.ClimbRate = 1;
		this.spnSectorSelector.Numeric = true;
		this.spnSectorSelector.SnapToTicks = true;
		this.hbox17.Add (this.spnSectorSelector);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.spnSectorSelector]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox17.Gtk.Box+BoxChild
		this.image257 = new global::Gtk.Image ();
		this.image257.Name = "image257";
		this.image257.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-index", global::Gtk.IconSize.Menu);
		this.hbox17.Add (this.image257);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.image257]));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		this.vbox10.Add (this.hbox17);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox17]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		this.hbox10.Add (this.vbox10);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.vbox10]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		this.vbox2.Add (this.hbox10);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox10]));
		w31.Position = 0;
		w31.Expand = false;
		w31.Fill = false;
		this.vbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w32.Position = 0;
		w32.Expand = false;
		w32.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox11 = new global::Gtk.VBox ();
		this.vbox11.Name = "vbox11";
		this.vbox11.Spacing = 6;
		// Container child vbox11.Gtk.Box+BoxChild
		this.cmbEditMode = global::Gtk.ComboBox.NewText ();
		this.cmbEditMode.AppendText (global::Mono.Unix.Catalog.GetString ("Select Sector (S)"));
		this.cmbEditMode.AppendText (global::Mono.Unix.Catalog.GetString ("Resize Sector (R)"));
		this.cmbEditMode.AppendText (global::Mono.Unix.Catalog.GetString ("Translate Sector (T)"));
		this.cmbEditMode.AppendText (global::Mono.Unix.Catalog.GetString ("Move Map(A)"));
		this.cmbEditMode.AppendText (global::Mono.Unix.Catalog.GetString ("Place Cursor (C)"));
		this.cmbEditMode.Name = "cmbEditMode";
		this.cmbEditMode.Active = 0;
		this.vbox11.Add (this.cmbEditMode);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.cmbEditMode]));
		w33.Position = 0;
		w33.Expand = false;
		w33.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.newSectorBtn = new global::Gtk.Button ();
		this.newSectorBtn.CanFocus = true;
		this.newSectorBtn.Name = "newSectorBtn";
		this.newSectorBtn.UseUnderline = true;
		// Container child newSectorBtn.Gtk.Container+ContainerChild
		global::Gtk.Alignment w34 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w35 = new global::Gtk.HBox ();
		w35.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w36 = new global::Gtk.Image ();
		w36.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
		w35.Add (w36);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w38 = new global::Gtk.Label ();
		w38.LabelProp = global::Mono.Unix.Catalog.GetString ("New Sector (N)");
		w38.UseUnderline = true;
		w35.Add (w38);
		w34.Add (w35);
		this.newSectorBtn.Add (w34);
		this.vbox11.Add (this.newSectorBtn);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.newSectorBtn]));
		w42.Position = 1;
		w42.Expand = false;
		w42.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.btnAddSolid = new global::Gtk.Button ();
		this.btnAddSolid.CanFocus = true;
		this.btnAddSolid.Name = "btnAddSolid";
		this.btnAddSolid.UseUnderline = true;
		// Container child btnAddSolid.Gtk.Container+ContainerChild
		global::Gtk.Alignment w43 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w44 = new global::Gtk.HBox ();
		w44.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w45 = new global::Gtk.Image ();
		w45.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
		w44.Add (w45);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w47 = new global::Gtk.Label ();
		w47.LabelProp = global::Mono.Unix.Catalog.GetString ("Add solid (D)");
		w47.UseUnderline = true;
		w44.Add (w47);
		w43.Add (w44);
		this.btnAddSolid.Add (w43);
		this.vbox11.Add (this.btnAddSolid);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.btnAddSolid]));
		w51.Position = 2;
		w51.Expand = false;
		w51.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.cmdAddDoor = new global::Gtk.Button ();
		this.cmdAddDoor.CanFocus = true;
		this.cmdAddDoor.Name = "cmdAddDoor";
		this.cmdAddDoor.UseUnderline = true;
		// Container child cmdAddDoor.Gtk.Container+ContainerChild
		global::Gtk.Alignment w52 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w53 = new global::Gtk.HBox ();
		w53.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w54 = new global::Gtk.Image ();
		w54.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-home", global::Gtk.IconSize.Menu);
		w53.Add (w54);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w56 = new global::Gtk.Label ();
		w56.LabelProp = global::Mono.Unix.Catalog.GetString ("Add proximity portal (P)");
		w56.UseUnderline = true;
		w53.Add (w56);
		w52.Add (w53);
		this.cmdAddDoor.Add (w52);
		this.vbox11.Add (this.cmdAddDoor);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.cmdAddDoor]));
		w60.Position = 3;
		w60.Expand = false;
		w60.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.addLampBtn = new global::Gtk.Button ();
		this.addLampBtn.CanFocus = true;
		this.addLampBtn.Name = "addLampBtn";
		this.addLampBtn.UseUnderline = true;
		// Container child addLampBtn.Gtk.Container+ContainerChild
		global::Gtk.Alignment w61 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w62 = new global::Gtk.HBox ();
		w62.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w63 = new global::Gtk.Image ();
		w63.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_add-bookmark", global::Gtk.IconSize.Menu);
		w62.Add (w63);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w65 = new global::Gtk.Label ();
		w65.LabelProp = global::Mono.Unix.Catalog.GetString ("Add light actor (L)");
		w65.UseUnderline = true;
		w62.Add (w65);
		w61.Add (w62);
		this.addLampBtn.Add (w61);
		this.vbox11.Add (this.addLampBtn);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.addLampBtn]));
		w69.Position = 4;
		w69.Expand = false;
		w69.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		// Container child button1.Gtk.Container+ContainerChild
		global::Gtk.Alignment w70 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w71 = new global::Gtk.HBox ();
		w71.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w72 = new global::Gtk.Image ();
		w72.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_person", global::Gtk.IconSize.Menu);
		w71.Add (w72);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w74 = new global::Gtk.Label ();
		w74.LabelProp = global::Mono.Unix.Catalog.GetString ("Add inteligent actor (I)");
		w74.UseUnderline = true;
		w71.Add (w74);
		w70.Add (w71);
		this.button1.Add (w70);
		this.vbox11.Add (this.button1);
		global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.button1]));
		w78.Position = 5;
		w78.Expand = false;
		w78.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.hbox16 = new global::Gtk.HBox ();
		this.hbox16.Name = "hbox16";
		this.hbox16.Spacing = 6;
		// Container child hbox16.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Actor Light Intensity:");
		this.hbox16.Add (this.label1);
		global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.label1]));
		w79.Position = 0;
		w79.Expand = false;
		w79.Fill = false;
		// Container child hbox16.Gtk.Box+BoxChild
		this.spnActorCandelas = new global::Gtk.SpinButton (0, 128, 1);
		this.spnActorCandelas.CanFocus = true;
		this.spnActorCandelas.Name = "spnActorCandelas";
		this.spnActorCandelas.Adjustment.PageIncrement = 10;
		this.spnActorCandelas.ClimbRate = 1;
		this.spnActorCandelas.Numeric = true;
		this.spnActorCandelas.Value = 128;
		this.hbox16.Add (this.spnActorCandelas);
		global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.spnActorCandelas]));
		w80.Position = 1;
		w80.Expand = false;
		w80.Fill = false;
		this.vbox11.Add (this.hbox16);
		global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox16]));
		w81.Position = 6;
		w81.Expand = false;
		w81.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox11.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hseparator1]));
		w82.Position = 7;
		w82.Expand = false;
		w82.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.newMapBtn = new global::Gtk.Button ();
		this.newMapBtn.CanFocus = true;
		this.newMapBtn.Name = "newMapBtn";
		this.newMapBtn.UseUnderline = true;
		// Container child newMapBtn.Gtk.Container+ContainerChild
		global::Gtk.Alignment w83 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w84 = new global::Gtk.HBox ();
		w84.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w85 = new global::Gtk.Image ();
		w85.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-new", global::Gtk.IconSize.Menu);
		w84.Add (w85);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w87 = new global::Gtk.Label ();
		w87.LabelProp = global::Mono.Unix.Catalog.GetString ("New map");
		w87.UseUnderline = true;
		w84.Add (w87);
		w83.Add (w84);
		this.newMapBtn.Add (w83);
		this.vbox11.Add (this.newMapBtn);
		global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.newMapBtn]));
		w91.Position = 8;
		w91.Expand = false;
		w91.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.openMapBtn = new global::Gtk.Button ();
		this.openMapBtn.CanFocus = true;
		this.openMapBtn.Name = "openMapBtn";
		this.openMapBtn.UseUnderline = true;
		// Container child openMapBtn.Gtk.Container+ContainerChild
		global::Gtk.Alignment w92 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w93 = new global::Gtk.HBox ();
		w93.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w94 = new global::Gtk.Image ();
		w94.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.Menu);
		w93.Add (w94);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w96 = new global::Gtk.Label ();
		w96.LabelProp = global::Mono.Unix.Catalog.GetString ("Import BZK2 map");
		w96.UseUnderline = true;
		w93.Add (w96);
		w92.Add (w93);
		this.openMapBtn.Add (w92);
		this.vbox11.Add (this.openMapBtn);
		global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.openMapBtn]));
		w100.Position = 9;
		w100.Expand = false;
		w100.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.btnImportLevel = new global::Gtk.Button ();
		this.btnImportLevel.CanFocus = true;
		this.btnImportLevel.Name = "btnImportLevel";
		this.btnImportLevel.UseUnderline = true;
		// Container child btnImportLevel.Gtk.Container+ContainerChild
		global::Gtk.Alignment w101 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w102 = new global::Gtk.HBox ();
		w102.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w103 = new global::Gtk.Image ();
		w103.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.Menu);
		w102.Add (w103);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w105 = new global::Gtk.Label ();
		w105.LabelProp = global::Mono.Unix.Catalog.GetString ("Import LEVEL map");
		w105.UseUnderline = true;
		w102.Add (w105);
		w101.Add (w102);
		this.btnImportLevel.Add (w101);
		this.vbox11.Add (this.btnImportLevel);
		global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.btnImportLevel]));
		w109.Position = 10;
		w109.Expand = false;
		w109.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.saveAsBtn = new global::Gtk.Button ();
		this.saveAsBtn.CanFocus = true;
		this.saveAsBtn.Name = "saveAsBtn";
		this.saveAsBtn.UseUnderline = true;
		// Container child saveAsBtn.Gtk.Container+ContainerChild
		global::Gtk.Alignment w110 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w111 = new global::Gtk.HBox ();
		w111.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w112 = new global::Gtk.Image ();
		w112.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save-as", global::Gtk.IconSize.Menu);
		w111.Add (w112);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w114 = new global::Gtk.Label ();
		w114.LabelProp = global::Mono.Unix.Catalog.GetString ("Save map as...");
		w114.UseUnderline = true;
		w111.Add (w114);
		w110.Add (w111);
		this.saveAsBtn.Add (w110);
		this.vbox11.Add (this.saveAsBtn);
		global::Gtk.Box.BoxChild w118 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.saveAsBtn]));
		w118.Position = 11;
		w118.Expand = false;
		w118.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.btnExport = new global::Gtk.Button ();
		this.btnExport.CanFocus = true;
		this.btnExport.Name = "btnExport";
		this.btnExport.UseUnderline = true;
		// Container child btnExport.Gtk.Container+ContainerChild
		global::Gtk.Alignment w119 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w120 = new global::Gtk.HBox ();
		w120.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w121 = new global::Gtk.Image ();
		w121.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-convert", global::Gtk.IconSize.Menu);
		w120.Add (w121);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w123 = new global::Gtk.Label ();
		w123.LabelProp = global::Mono.Unix.Catalog.GetString ("Apply portalization and export");
		w123.UseUnderline = true;
		w120.Add (w123);
		w119.Add (w120);
		this.btnExport.Add (w119);
		this.vbox11.Add (this.btnExport);
		global::Gtk.Box.BoxChild w127 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.btnExport]));
		w127.Position = 12;
		w127.Expand = false;
		w127.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.cmdQuit = new global::Gtk.Button ();
		this.cmdQuit.CanFocus = true;
		this.cmdQuit.Name = "cmdQuit";
		this.cmdQuit.UseUnderline = true;
		// Container child cmdQuit.Gtk.Container+ContainerChild
		global::Gtk.Alignment w128 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w129 = new global::Gtk.HBox ();
		w129.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w130 = new global::Gtk.Image ();
		w130.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-quit", global::Gtk.IconSize.Menu);
		w129.Add (w130);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w132 = new global::Gtk.Label ();
		w132.LabelProp = global::Mono.Unix.Catalog.GetString ("Quit");
		w132.UseUnderline = true;
		w129.Add (w132);
		w128.Add (w129);
		this.cmdQuit.Add (w128);
		this.vbox11.Add (this.cmdQuit);
		global::Gtk.Box.BoxChild w136 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.cmdQuit]));
		w136.Position = 13;
		w136.Expand = false;
		w136.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.status = new global::Gtk.Statusbar ();
		this.status.Name = "status";
		this.status.Spacing = 6;
		// Container child status.Gtk.Box+BoxChild
		this.image92 = new global::Gtk.Image ();
		this.image92.Name = "image92";
		this.image92.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
		this.status.Add (this.image92);
		global::Gtk.Box.BoxChild w137 = ((global::Gtk.Box.BoxChild)(this.status[this.image92]));
		w137.Position = 1;
		w137.Expand = false;
		w137.Fill = false;
		// Container child status.Gtk.Box+BoxChild
		this.lblCursorX = new global::Gtk.Label ();
		this.lblCursorX.Name = "lblCursorX";
		this.lblCursorX.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.status.Add (this.lblCursorX);
		global::Gtk.Box.BoxChild w138 = ((global::Gtk.Box.BoxChild)(this.status[this.lblCursorX]));
		w138.Position = 2;
		w138.Expand = false;
		w138.Fill = false;
		// Container child status.Gtk.Box+BoxChild
		this.lblCursorY = new global::Gtk.Label ();
		this.lblCursorY.Name = "lblCursorY";
		this.lblCursorY.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.status.Add (this.lblCursorY);
		global::Gtk.Box.BoxChild w139 = ((global::Gtk.Box.BoxChild)(this.status[this.lblCursorY]));
		w139.Position = 3;
		w139.Expand = false;
		w139.Fill = false;
		// Container child status.Gtk.Box+BoxChild
		this.lblCursorZ = new global::Gtk.Label ();
		this.lblCursorZ.Name = "lblCursorZ";
		this.lblCursorZ.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.status.Add (this.lblCursorZ);
		global::Gtk.Box.BoxChild w140 = ((global::Gtk.Box.BoxChild)(this.status[this.lblCursorZ]));
		w140.Position = 4;
		w140.Expand = false;
		w140.Fill = false;
		this.vbox11.Add (this.status);
		global::Gtk.Box.BoxChild w141 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.status]));
		w141.Position = 14;
		w141.Expand = false;
		w141.Fill = false;
		this.vbox1.Add (this.vbox11);
		global::Gtk.Box.BoxChild w142 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox11]));
		w142.Position = 1;
		w142.Expand = false;
		w142.Fill = false;
		this.hbox4.Add (this.vbox1);
		global::Gtk.Box.BoxChild w143 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox1]));
		w143.Position = 1;
		w143.Expand = false;
		w143.Fill = false;
		this.Add (this.hbox4);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnExposeEvent);
		this.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnKeyPressEvent);
		this.CBView1.Changed += new global::System.EventHandler (this.OnCBView1Changed);
		this.DA2.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnDA1ExposeEvent);
		this.DA2.ScrollEvent += new global::Gtk.ScrollEventHandler (this.OnDA1ScrollEvent);
		this.DA2.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnDA1ButtonPressEvent);
		this.DA2.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnDA1ButtonReleaseEvent);
		this.DA2.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.OnDA1MotionNotifyEvent);
		this.DA2.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnDA2KeyPressEvent);
		this.vsda2.ValueChanged += new global::System.EventHandler (this.OnVscrollbar2ValueChanged);
		this.hsda2.ValueChanged += new global::System.EventHandler (this.OnHsda2ValueChanged);
		this.CBView3.Changed += new global::System.EventHandler (this.OnCBView3Changed);
		this.DA3.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnDA3ExposeEvent);
		this.DA3.ScrollEvent += new global::Gtk.ScrollEventHandler (this.OnDA3ScrollEvent);
		this.DA3.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnDA3ButtonPressEvent);
		this.DA3.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnDA3ButtonReleaseEvent);
		this.DA3.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.OnDA3MotionNotifyEvent);
		this.DA3.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnDA3KeyPressEvent);
		this.vsda3.ValueChanged += new global::System.EventHandler (this.OnVsda3ValueChanged);
		this.hsda3.ValueChanged += new global::System.EventHandler (this.OnHsda3ValueChanged);
		this.vbox1.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnVbox1KeyPressEvent);
		this.cmbFaceSelection.Changed += new global::System.EventHandler (this.onCmbFaceSelectionChanged);
		this.clrSelection.Clicked += new global::System.EventHandler (this.onClrSelectionClicked);
		this.newSectorBtn.Clicked += new global::System.EventHandler (this.onNewSectorBtnClicked);
		this.btnAddSolid.Clicked += new global::System.EventHandler (this.OnBtnAddSolidClicked);
		this.cmdAddDoor.Clicked += new global::System.EventHandler (this.OnCmdAddDoorClicked);
		this.addLampBtn.Clicked += new global::System.EventHandler (this.onAddLampBtnClicked);
		this.newMapBtn.Clicked += new global::System.EventHandler (this.onNewMapBtnClicked);
		this.openMapBtn.Clicked += new global::System.EventHandler (this.onOpenMapBtnClicked);
		this.btnImportLevel.Clicked += new global::System.EventHandler (this.OnBtnImportLevelClicked);
		this.saveAsBtn.Clicked += new global::System.EventHandler (this.onSaveAsBtnClicked);
		this.btnExport.Clicked += new global::System.EventHandler (this.OnBtnExportClicked);
	}
}
