
// This file has been generated by the GUI designer. Do not modify.
namespace MonoBED3
{
	public partial class EditViewWidget
	{
		private global::Gtk.VBox vboxViewSelectorWidget;
		private global::Gtk.ComboBox cmbSelectView;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label lblZoom;
		private global::Gtk.SpinButton spnZoom;
		private global::Gtk.Label label1;
		private global::Gtk.CheckButton chkDrawGrid;
		private global::Gtk.CheckButton chkDrawExtendingLines;
		private global::Gtk.CheckButton chkDrawAsSolids;
		private global::Gtk.Button btnReset;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoBED3.EditViewWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoBED3.EditViewWidget";
			// Container child MonoBED3.EditViewWidget.Gtk.Container+ContainerChild
			this.vboxViewSelectorWidget = new global::Gtk.VBox ();
			this.vboxViewSelectorWidget.Name = "vboxViewSelectorWidget";
			this.vboxViewSelectorWidget.Spacing = 6;
			// Container child vboxViewSelectorWidget.Gtk.Box+BoxChild
			this.cmbSelectView = global::Gtk.ComboBox.NewText ();
			this.cmbSelectView.AppendText (global::Mono.Unix.Catalog.GetString ("XZ-View"));
			this.cmbSelectView.AppendText (global::Mono.Unix.Catalog.GetString ("XY-View"));
			this.cmbSelectView.AppendText (global::Mono.Unix.Catalog.GetString ("Toolbox"));
			this.cmbSelectView.Name = "cmbSelectView";
			this.cmbSelectView.Active = 0;
			this.vboxViewSelectorWidget.Add (this.cmbSelectView);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vboxViewSelectorWidget [this.cmbSelectView]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vboxViewSelectorWidget.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblZoom = new global::Gtk.Label ();
			this.lblZoom.Name = "lblZoom";
			this.lblZoom.LabelProp = global::Mono.Unix.Catalog.GetString ("Zoom");
			this.hbox1.Add (this.lblZoom);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblZoom]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.spnZoom = new global::Gtk.SpinButton (1, 255, 1);
			this.spnZoom.CanFocus = true;
			this.spnZoom.Name = "spnZoom";
			this.spnZoom.Adjustment.PageIncrement = 10;
			this.spnZoom.ClimbRate = 1;
			this.spnZoom.Numeric = true;
			this.spnZoom.Value = 1;
			this.hbox1.Add (this.spnZoom);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.spnZoom]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Draw:");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.chkDrawGrid = new global::Gtk.CheckButton ();
			this.chkDrawGrid.CanFocus = true;
			this.chkDrawGrid.Name = "chkDrawGrid";
			this.chkDrawGrid.Label = global::Mono.Unix.Catalog.GetString ("Grid");
			this.chkDrawGrid.DrawIndicator = true;
			this.chkDrawGrid.UseUnderline = true;
			this.hbox1.Add (this.chkDrawGrid);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.chkDrawGrid]));
			w5.Position = 3;
			// Container child hbox1.Gtk.Box+BoxChild
			this.chkDrawExtendingLines = new global::Gtk.CheckButton ();
			this.chkDrawExtendingLines.CanFocus = true;
			this.chkDrawExtendingLines.Name = "chkDrawExtendingLines";
			this.chkDrawExtendingLines.Label = global::Mono.Unix.Catalog.GetString ("Projection");
			this.chkDrawExtendingLines.DrawIndicator = true;
			this.chkDrawExtendingLines.UseUnderline = true;
			this.hbox1.Add (this.chkDrawExtendingLines);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.chkDrawExtendingLines]));
			w6.Position = 4;
			// Container child hbox1.Gtk.Box+BoxChild
			this.chkDrawAsSolids = new global::Gtk.CheckButton ();
			this.chkDrawAsSolids.CanFocus = true;
			this.chkDrawAsSolids.Name = "chkDrawAsSolids";
			this.chkDrawAsSolids.Label = global::Mono.Unix.Catalog.GetString ("Solid");
			this.chkDrawAsSolids.Active = true;
			this.chkDrawAsSolids.DrawIndicator = true;
			this.chkDrawAsSolids.UseUnderline = true;
			this.hbox1.Add (this.chkDrawAsSolids);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.chkDrawAsSolids]));
			w7.Position = 5;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnReset = new global::Gtk.Button ();
			this.btnReset.CanFocus = true;
			this.btnReset.Name = "btnReset";
			this.btnReset.UseUnderline = true;
			this.btnReset.Label = global::Mono.Unix.Catalog.GetString ("Reset");
			this.hbox1.Add (this.btnReset);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnReset]));
			w8.Position = 6;
			w8.Expand = false;
			w8.Fill = false;
			this.vboxViewSelectorWidget.Add (this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vboxViewSelectorWidget [this.hbox1]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.Add (this.vboxViewSelectorWidget);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnExposeEvent);
			this.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnKeyPressEvent);
			this.cmbSelectView.Changed += new global::System.EventHandler (this.OnCmbSelectViewChanged);
			this.spnZoom.ValueChanged += new global::System.EventHandler (this.OnSpnZoomValueChanged);
			this.chkDrawGrid.Toggled += new global::System.EventHandler (this.OnChkDrawGridToggled);
			this.chkDrawExtendingLines.Toggled += new global::System.EventHandler (this.OnChkDrawExtendingLinesToggled);
			this.chkDrawAsSolids.Toggled += new global::System.EventHandler (this.OnChkDrawSolidsToggled);
			this.btnReset.Clicked += new global::System.EventHandler (this.OnBtnResetClicked);
		}
	}
}
