/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.odb.derelict.editor;

import java.awt.Graphics;

/**
 *
 * @author monty
 */
public class MapViewPanel extends javax.swing.JPanel {

    SwingWorldRenderer renderer;
    EditorContext context;
    private int zoom;

    public int getZoom() {
        return zoom;
    }

    public void setZoom(int zoom) {
        this.zoom = zoom;
    }

    public EditorContext getContext() {
        return context;
    }

    public void setContext(EditorContext context) {
        this.context = context;
    }

    public SwingWorldRenderer getRenderer() {
        return renderer;
    }

    /**
     *
     * @param renderer
     */
    public void setRenderer(SwingWorldRenderer renderer) {
        this.renderer = renderer;
        repaint();
    }
    
    /**
     * Creates new form MapViewPanel
     */
    public MapViewPanel() {
        initComponents();
    }
    
    @Override
    public void paint( Graphics g ) {
        
        if ( context != null && renderer != null && context.getWorld() != null ) {
            
          //  renderer.setZoom( zoom );
            renderer.prepareWith( g );
            renderer.draw( context );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    void resetSize() {
        
    }
}
